/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
           /* Header fni.h>
/* Header for class com_iview_opencv_util_JniUtil */

#ifndef _Included_com_iview_opencv_util_JniUtil
#define _Included_com_iview_opencv_util_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iview_opencv_util_JniUtil
 * Method:    getString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iview_opencv_util_JniUtil_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
