/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iview_opencv_util_OpenCVHelper */

#ifndef _Included_com_iview_opencv_util_OpenCVHelper
#define _Included_com_iview_opencv_util_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iview_opencv_util_OpenCVHelper
 * Method:    detectPalmFromRawData
 * Signature: (Landroid/graphics/Bitmap;IILjava/lang/String;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_iview_opencv_util_OpenCVHelper_detectPalmFromRawData
  (JNIEnv *, jobject, jobject, jint, jint, jstring);

/*
 * Class:     com_iview_opencv_util_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_iview_opencv_util_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_iview_opencv_util_OpenCVHelper
 * Method:    getDealBitmap
 * Signature: (Landroid/graphics/Bitmap;II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_iview_opencv_util_OpenCVHelper_getDealBitmap
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
